DROP TABLE TBL_EMPLOYEE
DROP TABLE TBL_MENU
DROP TABLE TBL_BOARD
DROP TABLE TBL_CUSTOMER
DROP TABLE TBL_ORDER
DROP TABLE TBL_BOOK
DROP TABLE TBL_ITEM
DROP TABLE TBL_REPLY


CREATE TABLE TBL_EMPLOYEE(
	ID VARCHAR(50) PRIMARY KEY,
	PW VARCHAR(50) NOT NULL,	
    NAME VARCHAR(50) NOT NULL,
    POSITION VARCHAR(50) NOT NULL,
    DEPT VARCHAR(50) NOT NULL,
    PHONE VARCHAR(50) NOT NULL
)

CREATE TABLE TBL_CUSTOMER(
	ID VARCHAR(50) PRIMARY KEY,
	PW VARCHAR(50) NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	PHONE VARCHAR(50) NOT NULL,
	ADDR VARCHAR(50) NOT NULL
)

CREATE TABLE TBL_MENU(
	CODE VARCHAR(20) PRIMARY KEY,
	NAME VARCHAR(30) NOT NULL,
	PRICE INTEGER NOT NULL,
	IMAGE VARCHAR(30) NOT NULL
)

CREATE TABLE TBL_ORDER(
	CODE INTEGER PRIMARY KEY,
	CUSTOMER_ID VARCHAR(50) NOT NULL,
	ORDER_DATE VARCHAR(50) NOT NULL,
	TOTAL_PRICE INTEGER NOT NULL,
	DELEVERY INTEGER NOT NULL,
	CONSTRAINT FK_CID FOREIGN KEY(CUSTOMER_ID) REFERENCES TBL_CUSTOMER(ID)
)

CREATE TABLE TBL_ORDER_DETAIL(
	NO INTEGER PRIMARY KEY,
	ORDER_CODE INTEGER NOT NULL,
	MENU_CODE INTEGER NOT NULL,
	AMOUNT INTEGER NOT NULL,
	CONSTRAINT FK_MCODE FOREIGN KEY(MENU_CODE) REFERENCES TBL_ORDER(CODE)
)

CREATE TABLE TBL_BOARD(
	NO INTEGER PRIMARY KEY AUTO_INCREMENT,
	WRITER VARCHAR(50) NOT NULL,
	TITLE VARCHAR(50) NOT NULL,
	CONTENTS VARCHAR(300) NOT NULL,
	WDATE DATE NOT NULL,
	REPLYCNT INTEGER NOT NULL,
	READCNT INTEGER NOT NULL,
	CONSTRAINT FK_WRITER FOREIGN KEY(WRITER) REFERENCES TBL_CUSTOMER(ID)
)

CREATE TABLE TBL_REPLY(
	NO INTEGER PRIMARY KEY AUTO_INCREMENT,
	WRITER VARCHAR(50) NOT NULL,
	COMMENT VARCHAR(50) NOT NULL,
	WDATE DATE NOT NULL,
	B_NO INTEGER NOT NULL,
	CONSTRAINT FK_BNO FOREIGN KEY(B_NO) REFERENCES TBL_BOARD(NO)
)


